import { act, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { beforeEach, expect, it, vi } from "vitest";
import { memoryFixture } from "@/test/memory-fixture";
import { MemberNamesProvider } from "@/components/auth/member-names";
import type { MemoryItem } from "@/lib/memories/model";
const { read, save, load, subscribe } = vi.hoisted(() => ({ read: vi.fn(), save: vi.fn(), load: vi.fn(), subscribe: vi.fn() }));
vi.mock("@/lib/replies/actions", () => ({ readReplies: read, saveReply: save }));
vi.mock("@/lib/memories/actions", () => ({ loadMemories: load }));
vi.mock("@/lib/auth/browser", () => ({ gardenBrowserClient: () => ({}) }));
vi.mock("@/lib/garden/realtime", () => ({ subscribeGarden: subscribe }));
import { MemoriesClient } from "./memories-client";
const page = (items: MemoryItem[]) => ({ items, more: false, error: null });
const reply = (id: number, body = `Reply ${id}`) => ({ id, entry_id: 1, author_id: 2 as const, body, created_at: "2027-01-02T02:00:00Z" });
beforeEach(() => {
  vi.clearAllMocks();
  read.mockResolvedValue({ replies: [], error: null });
  load.mockResolvedValue(page([]));
  subscribe.mockReturnValue(() => {});
});
it.each([1, 2] as const)("lazily reads a bloomed entry for member %s with private author and original reply date, without composing", async memberId => {
  const original = memoryFixture("9007199254740993");
  const item = { ...original, flower: { ...original.flower, first_bloom_at: original.at, first_bloom_day: original.garden_day } };
  read.mockResolvedValue({ replies: [reply(1, "<script>Saved reply</script>")], error: null });
  const { unmount } = render(<MemberNamesProvider partnerName="Avery"><MemoriesClient initial={page([item])} memberId={memberId} /></MemberNamesProvider>);
  expect(read).not.toHaveBeenCalled();
  const toggle = screen.getByRole("button", { name: "Reply history" });
  expect(toggle).toHaveAttribute("aria-expanded", "false");
  fireEvent.click(toggle);
  const body = await screen.findByText("<script>Saved reply</script>");
  const history = within(body.closest("section")!);
  expect(read).toHaveBeenCalledWith("9007199254740993", null);
  expect(history.getByText(memberId === 1 ? "Avery" : "You")).toBeInTheDocument();
  expect(history.getByText(/Jan 1, 2027/)).toHaveAttribute("dateTime", "2027-01-02T02:00:00Z");
  expect(history.getByText(/6:00 PM PST/)).toBeInTheDocument();
  expect(document.querySelector("script, textarea, form:not([hidden])")).toBeNull();
  expect(screen.queryByRole("button", { name: /Send reply|Retry reply/ })).toBeNull();
  expect(save).not.toHaveBeenCalled();
  unmount();
  render(<MemoriesClient initial={page([item])} memberId={memberId} />);
  fireEvent.click(screen.getByRole("button", { name: "Reply history" }));
  await screen.findByText("<script>Saved reply</script>");
  expect(read).toHaveBeenCalledTimes(2);
});
it("attaches histories to the exact ordinary parents, including Dandelion details, but not summary cards", async () => {
  const base = memoryFixture();
  const detail: MemoryItem = { ...memoryFixture("2"), flower: { ...base.flower, type_key: "dandelion", shared_wish: "A shared wish" } };
  const wish: MemoryItem = { ...detail, kind: "wish", key: `wish:${base.flower.id}`, source_id: base.flower.id, entry: null };
  const peony: MemoryItem = { ...base, kind: "peony", key: `peony:${base.flower.id}`, source_id: base.flower.id, entry: null, flower: { ...base.flower, type_key: "peony" }, peony: { contributions: [], plan: null, completed: [] } };
  read.mockImplementation(async (entryId: string) => ({ replies: [reply(Number(entryId), `For entry ${entryId}`)], error: null }));
  render(<MemoriesClient initial={page([base, detail, wish, peony])} memberId={1} />);
  expect(screen.getAllByRole("button", { name: "Reply history" })).toHaveLength(2);
  const cards = screen.getAllByRole("article");
  for (const [index, id] of [[0, "1"], [1, "2"]] as const) {
    fireEvent.click(within(cards[index]).getByRole("button", { name: "Reply history" }));
    expect(await within(cards[index]).findByText(`For entry ${id}`)).toBeInTheDocument();
  }
  expect(screen.getAllByRole("article")).toEqual(cards);
});
it("shows loading, error/retry and empty states and rereads after collapsing", async () => {
  let finish!: (value: unknown) => void;
  read.mockReturnValueOnce(new Promise(resolve => { finish = resolve; }));
  render(<MemoriesClient initial={page([memoryFixture()])} memberId={2} />);
  const toggle = screen.getByRole("button", { name: "Reply history" });
  fireEvent.click(toggle);
  expect(await screen.findByText("Loading replies…")).toBeInTheDocument();
  expect(screen.queryByText("No replies yet.")).toBeNull();
  await waitFor(() => expect(read).toHaveBeenCalled());
  await act(async () => finish({ replies: [], error: "Replies unavailable" }));
  expect(screen.getByRole("alert")).toHaveTextContent("Replies unavailable");
  fireEvent.click(screen.getByRole("button", { name: "Reload replies" }));
  await screen.findByText("No replies yet.");
  fireEvent.click(toggle);
  expect(screen.queryByText("No replies yet.")).toBeNull();
  read.mockResolvedValueOnce({ replies: [reply(1)], error: null });
  fireEvent.click(toggle);
  await screen.findByText("Reply 1");
  expect(read).toHaveBeenCalledTimes(3);
  expect(save).not.toHaveBeenCalled();
});
it("paginates older replies in chronological order and retains them on older-page failure", async () => {
  read.mockResolvedValueOnce({ replies: Array.from({ length: 50 }, (_, i) => reply(i + 2)), error: null });
  render(<MemoriesClient initial={page([memoryFixture()])} memberId={1} />);
  fireEvent.click(screen.getByRole("button", { name: "Reply history" }));
  read.mockRejectedValueOnce(new Error("offline"));
  fireEvent.click(await screen.findByRole("button", { name: "Earlier replies" }));
  await screen.findByRole("alert");
  expect(screen.getByText("Reply 51")).toBeInTheDocument();
  read.mockResolvedValueOnce({ replies: [reply(1)], error: null });
  fireEvent.click(screen.getByRole("button", { name: "Earlier replies" }));
  await waitFor(() => expect(read).toHaveBeenCalledWith("1", 2));
  await waitFor(() => expect(screen.queryByRole("button", { name: "Earlier replies" })).toBeNull());
  const history = within(screen.getByRole("region", { name: "Replies" }));
  expect(history.getAllByRole("listitem")).toHaveLength(51);
  expect(history.getAllByRole("listitem")[0]).toHaveTextContent("Reply 1");
});
it.each(["manual", "realtime", "focus", "online", "visibilitychange", "fallback"])("refreshes an open history through %s without resetting expansion or original order", async trigger => {
  const interval = vi.spyOn(window, "setInterval");
  const item = memoryFixture();
  read.mockResolvedValueOnce({ replies: [reply(1)], error: null });
  render(<MemoriesClient initial={page([item])} memberId={1} />);
  const toggle = screen.getByRole("button", { name: "Reply history" });
  fireEvent.click(toggle);
  await screen.findByText("Reply 1");
  load.mockResolvedValueOnce(page([{ ...item, read_at: "2026-09-30T18:00:00Z" }])).mockResolvedValueOnce(page([]));
  read.mockResolvedValueOnce({ replies: [reply(1), reply(2)], error: null });
  if (trigger === "manual") fireEvent.click(screen.getByRole("button", { name: "Refresh memories" }));
  else if (trigger === "realtime") act(() => subscribe.mock.calls[0][1]());
  else if (trigger === "fallback") {
    const fallback = interval.mock.calls.find(([, delay]) => delay === 60_000)?.[0];
    expect(fallback).toBeTypeOf("function");
    act(() => (fallback as () => void)());
  } else fireEvent(trigger === "visibilitychange" ? document : window, new Event(trigger));
  await screen.findByText("Reply 2");
  expect(toggle).toHaveAttribute("aria-expanded", "true");
  expect(screen.getAllByRole("article")).toHaveLength(1);
  interval.mockRestore();
  expect(screen.queryByRole("button", { name: /newer memor/ })).toBeNull();
  expect(save).not.toHaveBeenCalled();
});
