begin;
create extension if not exists pgtap with schema extensions;
set local search_path=extensions,public,pg_catalog;
select no_plan();
select private.bootstrap_members('owner@example.test','member@example.test');
insert into auth.users(id,aud,role,email,email_confirmed_at,raw_app_meta_data) values
 ('11111111-1111-4111-8111-111111111111','authenticated','authenticated','owner@example.test',now(),'{"provider":"google","providers":["google"]}'),
 ('22222222-2222-4222-8222-222222222222','authenticated','authenticated','member@example.test',now(),'{"provider":"google","providers":["google"]}'),
 ('33333333-3333-4333-8333-333333333333','authenticated','authenticated','outsider@example.test',now(),'{"provider":"google","providers":["google"]}');
insert into auth.identities(user_id,provider_id,provider,identity_data) values
 ('11111111-1111-4111-8111-111111111111','peony-owner','google','{"sub":"peony-owner","email":"owner@example.test","email_verified":true}'),
 ('22222222-2222-4222-8222-222222222222','peony-member','google','{"sub":"peony-member","email":"member@example.test","email_verified":true}'),
 ('33333333-3333-4333-8333-333333333333','peony-outsider','google','{"sub":"peony-outsider","email":"outsider@example.test","email_verified":true}');
create function pg_temp.actor(n integer) returns void language sql as $$
 select set_config('request.jwt.claims',jsonb_build_object('sub',case n when 1 then '11111111-1111-4111-8111-111111111111' when 2 then '22222222-2222-4222-8222-222222222222' else '33333333-3333-4333-8333-333333333333' end,'role','authenticated','amr',jsonb_build_array(jsonb_build_object('method','oauth')))::text,true);
$$;
select pg_temp.actor(1);
select public.initialize_garden();
select throws_ok($$select private.bootstrap_private_interaction(1::smallint,'Synthetic title','Synthetic private marker 36','[{"key":"yes","label":"Option A"},{"key":"later","label":"Option B"}]')$$,'22023',null,'owner cannot be configured as recipient');
select throws_ok($$select private.bootstrap_private_interaction(2::smallint,'Synthetic title','Synthetic private marker 36','[{"key":"same","label":"Option A"},{"key":"same","label":"Option B"}]')$$,'22023',null,'duplicate answer keys rejected');
select throws_ok($$select private.bootstrap_private_interaction(2::smallint,'Synthetic title','Synthetic private marker 36','[{"key":"bad key","label":"Option A"},{"key":"b","label":"Option B"}]')$$,'22023',null,'unbounded key syntax rejected');
select throws_ok($$select private.bootstrap_private_interaction(2::smallint,'Synthetic title',repeat('x',4001),'[{"key":"a","label":"Option A"},{"key":"b","label":"Option B"}]')$$,'22023',null,'oversized text rejected');
select throws_ok($$select private.bootstrap_private_interaction(2::smallint,'Synthetic title','Synthetic text',null)$$,'22023',null,'null choices rejected');
select throws_ok($$select private.bootstrap_private_interaction(2::smallint,'Synthetic title','Synthetic text','{"key":"a","label":"A"}')$$,'22023',null,'non-array choices rejected');
select throws_ok($$select private.bootstrap_private_interaction(2::smallint,'Synthetic title','Synthetic text','[{"key":"a","label":"A"}]')$$,'22023',null,'one choice rejected');
select throws_ok($$select private.bootstrap_private_interaction(2::smallint,'Synthetic title','Synthetic text','[{"key":"a","label":"A","html":"<b>unsafe</b>"},{"key":"b","label":"B"}]')$$,'22023',null,'arbitrary fields rejected');
select throws_ok($$select private.bootstrap_private_interaction(2::smallint,'Synthetic title','Synthetic text',jsonb_build_array(jsonb_build_object('key','a','label',repeat(' ',120)||'A'),jsonb_build_object('key','b','label','B')))$$,'22023',null,'padding cannot evade label bound');
select throws_ok($$select private.bootstrap_private_interaction(2::smallint,repeat('x',161),'Synthetic text','[{"key":"a","label":"A"},{"key":"b","label":"B"}]')$$,'22023',null,'oversized title rejected');
set local role authenticated;
select pg_temp.actor(2);
select is(public.current_private_interaction()->>'status','unavailable','unconfigured recipient fails closed');
select throws_ok($$select public.owner_private_interaction('status')$$,'42501',null,'partner cannot probe owner status');
select throws_ok($$select public.owner_private_interaction('preview')$$,'42501',null,'partner cannot probe preview');
select throws_ok($$select public.owner_private_interaction('arm',true)$$,'42501',null,'partner cannot arm');
select throws_ok($$select public.owner_private_interaction('acknowledge')$$,'42501',null,'partner cannot acknowledge');
select throws_ok($$select * from private.private_interaction_config$$,'42501',null,'private table denied');
select throws_ok($$select * from private.private_interaction_delivery$$,'42501',null,'answer table denied');
reset role;
select private.bootstrap_private_interaction(2::smallint,'Synthetic title','Synthetic private marker 36','[{"key":"a","label":"Option A"},{"key":"b","label":"Option B"}]');
select is((select armed from private.private_interaction_config),true,'armed by default');
select lives_ok($$select private.bootstrap_private_interaction(2::smallint,'Synthetic title','Synthetic private marker 36','[{"key":"a","label":"Option A"},{"key":"b","label":"Option B"}]')$$,'identical private bootstrap is idempotent');
select throws_ok($$select private.bootstrap_private_interaction(2::smallint,'Changed title','Synthetic private marker 36','[{"key":"a","label":"Option A"},{"key":"b","label":"Option B"}]')$$,'22023',null,'configuration is immutable');
set local role authenticated;
select pg_temp.actor(1);
select is(public.owner_private_interaction('preview')->'content'->>'message','Synthetic private marker 36','owner can preview private copy');
select is(public.owner_private_interaction('status')->>'status','ready','owner sees armed waiting status');
select is(public.current_private_interaction()->>'status','owner','owner cannot receive real event');
reset role;
select is((select count(*) from private.private_interaction_delivery),0::bigint,'preview never creates delivery');
select is((select count(*) from public.private_interaction_signals),0::bigint,'preview never notifies');
insert into public.achievement_awards(achievement_id,earned_at) select achievement_id,clock_timestamp() from public.achievement_catalog where position<26;
set local role authenticated;
select pg_temp.actor(2);
select is(public.current_private_interaction(),' {"status":"unavailable"}'::jsonb,'25 awards never reveals content');
select throws_ok($$select public.answer_private_interaction('a')$$,'22023',null,'25 awards cannot answer');
reset role;
insert into public.achievement_awards(achievement_id,earned_at) select achievement_id,clock_timestamp() from public.achievement_catalog where position=26;
set local role authenticated;
select pg_temp.actor(1);
select is(public.owner_private_interaction('arm',false)->>'armed','false','owner disarms');
select pg_temp.actor(2);
select is(public.current_private_interaction(),' {"status":"unavailable"}'::jsonb,'all26 disarmed hides content');
select throws_ok($$select public.answer_private_interaction('a')$$,'22023',null,'disarmed cannot answer');
reset role;
select is((select count(*) from private.private_interaction_delivery),0::bigint,'disarmed never creates pending');
set local role authenticated;
select pg_temp.actor(1);
select public.owner_private_interaction('arm',true);
select pg_temp.actor(2);
select throws_ok($$select public.answer_private_interaction('a')$$,'22023',null,'answer requires prior delivery');
select is(public.current_private_interaction()->>'status','pending','all26 receives pending');
select is(public.current_private_interaction()->'content'->>'message','Synthetic private marker 36','eligible recipient receives private copy');
reset role;
create temporary table initial_delivery as select * from private.private_interaction_delivery;
create temporary table before_garden as select to_jsonb(f) value from public.flowers f;
set local role authenticated;
select is(public.current_private_interaction()->>'status','pending','refresh retains pending');
select throws_ok($$select public.answer_private_interaction('forged')$$,'22023',null,'unconfigured answer cannot be saved');
select pg_temp.actor(1);
select public.owner_private_interaction('arm',false);
select pg_temp.actor(2);
select is(public.current_private_interaction()->>'status','unavailable','disarm suppresses existing pending');
select throws_ok($$select public.answer_private_interaction('a')$$,'22023',null,'stale open recipient cannot answer after disarm');
select pg_temp.actor(1);
select public.owner_private_interaction('preview');
select public.owner_private_interaction('arm',true);
select pg_temp.actor(2);
select is(public.current_private_interaction()->>'status','pending','rearm resumes pending');
reset role;
select is((select delivered_at from private.private_interaction_delivery),(select delivered_at from initial_delivery),'refresh/disarm/rearm preserve original delivery');
set local role authenticated;
select pg_temp.actor(1);
select throws_ok($$select public.answer_private_interaction('a')$$,'42501',null,'owner cannot answer the real event');
select pg_temp.actor(2);
select is(public.answer_private_interaction('b')->>'status','answered','recipient saves answer');
select is(public.current_private_interaction(),' {"status":"answered"}'::jsonb,'answered never prompts or includes copy');
select is(public.answer_private_interaction('b')->>'status','answered','same-key answer replay is idempotent');
select is(public.answer_private_interaction('a')->>'status','answered','different-key replay cannot replace first answer');
select throws_ok($$select public.answer_private_interaction(repeat('x',49))$$,'22023',null,'oversized answer key is rejected even after answer');
select is((select count(*) from public.private_interaction_signals),0::bigint,'partner cannot read owner signal');
select throws_ok($$update public.private_interaction_signals set revision=99$$,'42501',null,'signal direct write denied');
select pg_temp.actor(1);
select is(public.owner_private_interaction('status')->'answer'->>'key','b','original answer retained');
select is(public.owner_private_interaction('status')->'answer'->>'label','Option B','original label retained');
select is(public.owner_private_interaction('status')->>'unread','true','owner has durable unread answer');
select is((select count(*) from public.private_interaction_signals),1::bigint,'only owner can read signal');
select public.owner_private_interaction('arm',false);
select public.owner_private_interaction('arm',true);
select is(public.owner_private_interaction('status')->>'status','answered','arm controls cannot reset answer');
select is(public.owner_private_interaction('acknowledge')->>'unread','false','owner acknowledges notification');
reset role;
create temporary table original_answer as select * from private.private_interaction_delivery;
create temporary table original_signal as select * from public.private_interaction_signals;
set local role authenticated;
select public.owner_private_interaction('acknowledge');
select public.owner_private_interaction('status');
select public.owner_private_interaction('preview');
select pg_temp.actor(2);
select public.current_private_interaction();
select public.answer_private_interaction('a');
select pg_temp.actor(3);
select throws_ok($$select public.current_private_interaction()$$,'42501',null,'outsider read denied');
select throws_ok($$select public.answer_private_interaction('a')$$,'42501',null,'outsider answer denied');
select throws_ok($$select public.owner_private_interaction('preview')$$,'42501',null,'outsider preview denied');
select is((select count(*) from public.private_interaction_signals),0::bigint,'outsider signal hidden');
reset role;
select is((select to_jsonb(d) from private.private_interaction_delivery d),(select to_jsonb(d) from original_answer d),'answer actor/time/ack are immutable on all retries');
select is((select answered_by from private.private_interaction_delivery),2::smallint,'actor comes from membership');
select ok((select answered_at>=delivered_at and acknowledged_at>=answered_at from private.private_interaction_delivery),'server times ordered');
select is((select to_jsonb(s) from public.private_interaction_signals s),(select to_jsonb(s) from original_signal s),'reads and repeated acknowledgment never write notification');
select is((select count(*) from private.private_interaction_delivery),1::bigint,'at most one delivery');
select is((select count(*) from public.achievement_catalog),26::bigint,'interaction excluded from ordinary denominator');
select is((select jsonb_agg(to_jsonb(f) order by spot) from public.flowers f),(select jsonb_agg(value order by (value->>'spot')::integer) from before_garden),'display effect never changes flowers');
select is((select count(*) from public.flower_day_facts),0::bigint,'no invented growth facts');
select ok(not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='private'),'no private payload publication');
select ok(not has_table_privilege('service_role','private.private_interaction_config','select'),'service-role direct private config denied');
set local role authenticated;
select pg_temp.actor(1);
select throws_ok($$select public.owner_private_interaction('unknown')$$,'22023',null,'unknown admin command rejected');
select throws_ok($$select public.owner_private_interaction('arm',null)$$,'22023',null,'null armed state rejected');
select pg_temp.actor(2);
select set_config('request.jwt.claims','{"sub":"22222222-2222-4222-8222-222222222222","role":"authenticated","member_role":"owner","user_metadata":{"member_id":1,"complete":true},"amr":[{"method":"oauth"}]}',true);
select throws_ok($$select public.owner_private_interaction('preview')$$,'42501',null,'forged metadata never grants owner');
reset role;
update private.garden_members set revoked_at=clock_timestamp() where member_id=1;
set local role authenticated;
select pg_temp.actor(1);
select throws_ok($$select public.owner_private_interaction('status')$$,'42501',null,'revoked owner cannot read answer');
select is((select count(*) from public.private_interaction_signals),0::bigint,'revoked owner cannot read signal');
reset role;
update private.garden_members set revoked_at=clock_timestamp() where member_id=2;
set local role authenticated;
select pg_temp.actor(2);
select throws_ok($$select public.current_private_interaction()$$,'42501',null,'revoked recipient cannot read state');
select throws_ok($$select public.answer_private_interaction('a')$$,'42501',null,'revoked recipient cannot replay answer');
reset role;
set local role anon;
select throws_ok($$select public.current_private_interaction()$$,'42501',null,'anonymous read denied');
select throws_ok($$select public.owner_private_interaction('preview')$$,'42501',null,'anonymous preview denied');
select throws_ok($$select public.answer_private_interaction('a')$$,'42501',null,'anonymous answer denied');
reset role;
select * from finish();
rollback;
